from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')

old_version = '<meta name="app-version" content="2026-09-04-ficha-cadastro-modal-1" />'
new_version = '<meta name="app-version" content="2026-09-04-carrinho-esquerda-item-1" />'
if old_version in s:
    s = s.replace(old_version, new_version, 1)
elif new_version not in s:
    raise SystemExit('app version marker not found')

old_item = '''                              <td className="py-2.5 pr-3 sticky left-0 bg-white z-10">\n                                {linha.tipo === 'revenda' ? (\n                                  <input value={x.productName} onChange={(e) => onUpdateSeparatedProduct({...x,productName:e.target.value})} className="field h-8 px-2.5 text-[13px] font-semibold w-36 sm:w-48" />\n                                ) : linha.tipo === 'insumo_revenda' ? (\n                                  <input\n                                    value={x.name}\n                                    onChange={(e) => {\n                                      const name = e.target.value;\n                                      onUpdateSupply({...x,name});\n                                      if (linha.resaleSource) onUpdateSeparatedProduct({...linha.resaleSource,productName:name});\n                                    }}\n                                    className="field h-8 px-2.5 text-[13px] font-semibold w-36 sm:w-48"\n                                  />\n                                ) : ehSupply ? (\n                                  <input value={x.name} onChange={(e) => onUpdateSupply({...x,name:e.target.value})} className="field h-8 px-2.5 text-[13px] font-semibold w-36 sm:w-48" />\n                                ) : (\n                                  <input value={x.name} onChange={(e) => onUpdateProduct({...x,name:e.target.value})} className="field h-8 px-2.5 text-[13px] font-semibold w-36 sm:w-48" />\n                                )}\n                              </td>\n'''

new_item = '''                              <td className="py-2.5 pr-3 sticky left-0 bg-white z-10">\n                                <div className="flex items-center gap-1.5">\n                                  {linha.tipo !== 'producao' && (\n                                    <button\n                                      type="button"\n                                      onClick={() => setHistorico(linha.tipo === 'revenda' ? { tipo: 'revenda', id: x.id } : { tipo: 'insumo', id: x.id })}\n                                      title={`Histórico de compras${comprasLinha.length ? ` · ${comprasLinha.length}` : ''}`}\n                                      className="w-8 h-8 rounded-full bg-black/[0.05] hover:bg-black/[0.09] flex items-center justify-center relative shrink-0"\n                                    >\n                                      <Icons.ShoppingCart className="w-3.5 h-3.5" />\n                                      {comprasLinha.length > 1 && <span className="absolute -top-1 -right-1 min-w-4 h-4 px-1 text-[9px] font-bold rounded-full bg-[#0E0937] text-white flex items-center justify-center tnum">{comprasLinha.length}</span>}\n                                    </button>\n                                  )}\n                                  {linha.tipo === 'revenda' ? (\n                                    <input value={x.productName} onChange={(e) => onUpdateSeparatedProduct({...x,productName:e.target.value})} className="field h-8 px-2.5 text-[13px] font-semibold w-36 sm:w-48" />\n                                  ) : linha.tipo === 'insumo_revenda' ? (\n                                    <input\n                                      value={x.name}\n                                      onChange={(e) => {\n                                        const name = e.target.value;\n                                        onUpdateSupply({...x,name});\n                                        if (linha.resaleSource) onUpdateSeparatedProduct({...linha.resaleSource,productName:name});\n                                      }}\n                                      className="field h-8 px-2.5 text-[13px] font-semibold w-36 sm:w-48"\n                                    />\n                                  ) : ehSupply ? (\n                                    <input value={x.name} onChange={(e) => onUpdateSupply({...x,name:e.target.value})} className="field h-8 px-2.5 text-[13px] font-semibold w-36 sm:w-48" />\n                                  ) : (\n                                    <input value={x.name} onChange={(e) => onUpdateProduct({...x,name:e.target.value})} className="field h-8 px-2.5 text-[13px] font-semibold w-36 sm:w-48" />\n                                  )}\n                                </div>\n                              </td>\n'''

if old_item not in s:
    raise SystemExit('catalog item cell not found')
s = s.replace(old_item, new_item, 1)

old_actions = '''                              <td className="py-2.5 pl-3">\n                                <div className="flex items-center justify-end gap-1.5 min-w-[120px]">\n                                  {linha.tipo === 'producao' ? (\n                                    <button type="button" onClick={() => setFichaProdutoId(x.id)} title="Abrir ficha técnica" className="w-8 h-8 rounded-full bg-black/[0.05] hover:bg-black/[0.09] flex items-center justify-center">\n                                      <Icons.ClipboardList className="w-3.5 h-3.5" />\n                                    </button>\n                                  ) : (\n                                    <button\n                                      type="button"\n                                      onClick={() => setHistorico(linha.tipo === 'revenda' ? { tipo: 'revenda', id: x.id } : { tipo: 'insumo', id: x.id })}\n                                      title={`Histórico de compras${comprasLinha.length ? ` · ${comprasLinha.length}` : ''}`}\n                                      className="w-8 h-8 rounded-full bg-black/[0.05] hover:bg-black/[0.09] flex items-center justify-center relative"\n                                    >\n                                      <Icons.ShoppingCart className="w-3.5 h-3.5" />\n                                      {comprasLinha.length > 1 && <span className="absolute -top-1 -right-1 min-w-4 h-4 px-1 text-[9px] font-bold rounded-full bg-[#0E0937] text-white flex items-center justify-center tnum">{comprasLinha.length}</span>}\n                                    </button>\n                                  )}\n                                  <button type="button" onClick={() => onDeleteCatalogItem(linha)} title={`Remover ${linha.name}`} className="w-8 h-8 rounded-full icon-danger flex items-center justify-center">\n                                    <Icons.Trash2 className="w-4 h-4" />\n                                  </button>\n                                </div>\n                              </td>\n'''

new_actions = '''                              <td className="py-2.5 pl-3">\n                                <div className="flex items-center justify-end gap-1.5 min-w-[80px]">\n                                  {linha.tipo === 'producao' && (\n                                    <button type="button" onClick={() => setFichaProdutoId(x.id)} title="Abrir ficha técnica" className="w-8 h-8 rounded-full bg-black/[0.05] hover:bg-black/[0.09] flex items-center justify-center">\n                                      <Icons.ClipboardList className="w-3.5 h-3.5" />\n                                    </button>\n                                  )}\n                                  <button type="button" onClick={() => onDeleteCatalogItem(linha)} title={`Remover ${linha.name}`} className="w-8 h-8 rounded-full icon-danger flex items-center justify-center">\n                                    <Icons.Trash2 className="w-4 h-4" />\n                                  </button>\n                                </div>\n                              </td>\n'''

if old_actions not in s:
    raise SystemExit('catalog actions cell not found')
s = s.replace(old_actions, new_actions, 1)

if s.count('title={`Histórico de compras${comprasLinha.length ? ` · ${comprasLinha.length}` : \'\'}`}') != 1:
    raise SystemExit('expected exactly one master-table purchase history button')
if '2026-09-04-carrinho-esquerda-item-1' not in s:
    raise SystemExit('version marker missing')

p.write_text(s, encoding='utf-8')
